language: python

python:
  - "3.8"

env:
  - DB=pg PGSQL_USER=postgres PGSQL_USER=

services:
  - postgresql
  - memcached

before_script:
  - psql -c 'drop database if exists test_olo;' -U postgres
  - psql -c 'create database test_olo;' -U postgres
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install pylint==2.4.4 codecov

script:
  - pylint --rcfile=.pylintrc olo
  - pytest --cov=olo

after_success:
  - codecov
